# A config file for your Supabase project
# https://supabase.com/docs/reference/cli/config

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = false
port = 54324

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[edge_functions]
enabled = true
port = 54326

[analytics]
enabled = false
port = 54327